[phases.setup]
nixPkgs = ['nodejs']

[phases.install]
cmds = [
  'cd client && npm install',
  'cd ../server && npm install'
]

[phases.build]
cmds = [
  'mkdir -p server/public',
  'cd client && npm run build',
  'cp -r client/dist/* server/public/'
]

[start]
cmd = 'cd server && npm start'