[build]
builder = "NIXPACKS"
buildCommand = "cd client && npm install && npm run build"

[deploy]
startCommand = "cd server && npm install && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[variables]
NODE_ENV = "production"