[phases.setup]
nixPkgs = ['nodejs']

[phases.install]
cmds = [
  'cd client && npm install',
  'cd ../server && npm install'
]

[phases.build]
cmds = [
  'cd client && npm run build',
  'cd ../server && echo "No build required for server"'
]

[start]
cmd = 'cd server && npm start'